### ISSUE TITLE
No url bar on touch launch?

### ISSUE THREAD

**Issue by bkardell** [brave/browser-android#666]
When I install brave for android, it wires into the underlying OS stuff / content type handling so if I try to view a page through search or twitter or something I can open it with brave, but if I simply click/launch it, it doesn't seem to have a url bar or any way for me to go anywhere. Seems confusing?

![screenshot_2016-01-26-19-14-36](https://cloud.githubusercontent.com/assets/870501/12599661/e362af3e-c461-11e5-9293-f219ca79e075.png)

**Comment by SergeyZhukovsky** [comment]
Hi @bkardel,
Ya, we want to add it on that page soon,
Thanks for the opened issue.

**Comment by SergeyZhukovsky** [comment]
Hi @bkardell,
It is corrected in a new version. There is a button "NEW BUBBLE" on the main page.
Thanks.
