### ISSUE TITLE
Problem with Brave and updated release of Google Drive

### ISSUE THREAD

**Issue by Dirtyblckpistol** [brave/browser-android#669]
So layman terms i updated google drive on my device last night, then if i went to use brave  i would use the bubble to open a new tab.. but instead it kept trying to open drive giving me an error. So i disabled drive and it works fine again. I am running 6.0.1 on an htc A9 . Google rive version affecting brave is 2.3.544.17.45

I hope you can understand what i mean.

**Comment by Dirtyblckpistol** [comment]
![screenshot_20160128-064642](https://cloud.githubusercontent.com/assets/16938671/12647666/1c4c23a0-c58b-11e5-8a7e-a72cf5735940.png)

**Comment by SergeyZhukovsky** [comment]
Hi @Dirtyblckpistol,
Thanks for the pic.
We are working on it.

**Comment by Dirtyblckpistol** [comment]
no problem i only know basics and marketing stuff . so i was not sure how to explain it. If you need anything more just reach out to me.

Thank you

**Comment by SergeyZhukovsky** [comment]
Hi @Dirtyblckpistol,
Could you please try a new 1.7.9 release.
Let us know, if you still have that problem.
Thanks.

**Comment by Dirtyblckpistol** [comment]
It's good to go Serg..  Awesome work you guys!

**Comment by Dirtyblckpistol** [comment]
It's good to go Serg..  Awesome work you guys!
