### ISSUE TITLE
Brave app not getting opened in Android 5.0.2 LRX22G build running in Xiaomi Mi4i (MIUI 7.1.1.0 build)

### ISSUE THREAD

**Issue by happyvig** [brave/browser-android#672]
I have installed Brave app in my Xiaomi Mi4i (MIUI 7.1.1.0 build) mobile running Android 5.0.2 LRX22G build. The app is not even getting opened when I click some links in my mail and try to navigate to the page via Brave app.

**Comment by SergeyZhukovsky** [comment]
Thanks for posting that.
We are looking on that issue.

**Comment by SergeyZhukovsky** [comment]
Hi @happyvig. Could you please check that you have that permission on for Brave on your device?
You should grant the permission to pop UP windows.

**Comment by happyvig** [comment]
Thanks. Its working fine now.
