### ISSUE TITLE
1.7.9 fails to load any link

### ISSUE THREAD

**Issue by bengarnett** [brave/browser-android#673]
First turned off HTTPS everywhere to no effect, then downgraded to 1.7.8 nexus 5

**Comment by SergeyZhukovsky** [comment]
Thanks @bengarnett. We are working on that problem.
It'll be fixed in next release.

**Comment by bengarnett** [comment]
Also occurred on 1.7.8. Update to 1.7.9 fixed this time

**Comment by bengarnett** [comment]
Has not yet occurred on 1.8, day 1

**Comment by SergeyZhukovsky** [comment]
Great.
Thanks for trying it.
