### ISSUE TITLE
Current linkbubble blank after resume from unlock

### ISSUE THREAD

**Issue by bengarnett** [brave/browser-android#676]
1.8.0, nexus 5

To recreate. Hit power button, unlock phone. Current linkbubble is blank.

Workaround. Focus another link bubble and click back to the original one

**Comment by SergeyZhukovsky** [comment]
Done
https://github.com/brave/browser-android/commit/1166c94ece2fa6fb1386e5b1754120bb47113646
Should be fixed in next build.
