### ISSUE TITLE
Brave hanging on first launch

### ISSUE THREAD

**Issue by swarnava** [brave/browser-android#677]
When i tried to launch brave first time on android, It hanged for 10-15 seconds, and need to force close twice. I tried several time with clearing the data and reproduce this issue and its reproducible easily.

let me know if any logs are needed!

Device: Nexus 4 running Android 5.1.1 Stock

**Comment by SergeyZhukovsky** [comment]
Fixed it
https://github.com/brave/browser-android/commit/dc6fdc8db86cd0587619f772ca59a2c7ef9f2ea5
The fix will be available on next release.
Thanks @swarnava for posting that!
