### ISSUE TITLE
Brave does not recognize all possible fallback browsers

### ISSUE THREAD

**Issue by ineptules** [brave/browser-android#695]
Unable to set certain browsers like Lightning Browser or CAF Chromium as the default fallback browser.

**Comment by zmni** [comment]
Also Brave doesn't recognize Chromium for Android (latest snapshots downloaded from https://download-chromium.appspot.com/?platform=Android ).

Brave 1.9.14
Android 4.4.2

**Comment by bbondy** [comment]
Lightning should work with the latest, let me know if not. 
Anyone know the app id for Chromium?

**Comment by zmni** [comment]
Is `org.chromium.chrome` what you looking for? It's listed in my /data/data/ folder on my phone.
If not, where can I look?

**Comment by weems** [comment]
I believe that @zmni is correct. For possible clarification in the Play Store the Page for 'Chrome Dev (com.chrome.dev)' is the following: https://play.google.com/store/apps/details?id=com.chrome.dev

**Comment by SergeyZhukovsky** [comment]
Added Chromium to the list.
https://github.com/brave/browser-android/commit/5a72431e4999ff59e46641ff61dee543f31765f6
