### ISSUE TITLE
Very high battery usage on COS 12.1

### ISSUE THREAD

**Issue by jomahoney** [brave/browser-android#708]
### Issue Summary
I seem to be having very high battery usage on my phone, most of which seems to be coming from an active radio signal.

### Steps to Reproduce

1. Download and run on COS12.1
2. Run the app and don't force stop it.

Here are some screenshots of the issue:
<img src="https://cloud.githubusercontent.com/assets/1396009/13593864/39e3070e-e4f7-11e5-9d2f-93e95e687b09.png" width="256px" />
<img src="https://cloud.githubusercontent.com/assets/1396009/13593869/404a944a-e4f7-11e5-9455-bdef964b5aad.png" width="256px" />

### Technical details:

* Brave Version: 1.9.2
* Android OS: COS12.1 (12.1-YOG4PAS1NO)
* Android Version: 5.1.1

Could possibly be related to #614, if so please feel free to close.

**Comment by jomahoney** [comment]
This seems to have been an isolated incident, caused by a page on a refresh loop.

**Comment by bbondy** [comment]
any steps to reproduce or page which can reproduce? Thanks.
