### ISSUE TITLE
Rendering issue of bubbles

### ISSUE THREAD

**Issue by Kurre** [brave/browser-android#718]
I'm facing very strange problems with latest builds.

Sometimes bubbles behave and render very strangely and this usually makes it almost impossible to use the browser. Bubbles render incorrectly and I can't even open 'em. This issue came with 1.9.6 build (and is still present in 1.9.7 build).

See included video: https://www.dropbox.com/s/890ggiiw5dcxvgg/2016_03_19_08_43_41.mp4?dl=0

Usually this happens when I press home button to "exit" the browser. When I manually launch Brave's main app and create a new bubble, all bubbles, kind of, rerender and behave correctly, until I leave the browser again.

I'm using OnePlus One with SlimSaber ROM (Android 6.0.1) which is based on Omnirom, with slightly lower dpi value than stock (420 vs 480).

I'm more than happy to provide more information if needed.

**Comment by SergeyZhukovsky** [comment]
Thank you very much @Kurre. Fixed it here
https://github.com/brave/browser-android/commit/30efbefd96743fe16ae6343a9f867859c52bb5d1
and releasing a new 1.9.8 update.
Thank you again for helping with our application!!!
