### ISSUE TITLE
Fix description of HTTPS-everywhere

### ISSUE THREAD

**Issue by oldhill** [brave/browser-android#719]
[This line](https://github.com/brave/browser-android/blob/63f78701b176c34a35158f35e09ddea03b0c7ce8/Application/LinkBubble/src/main/res/values/strings.xml#L140) should read: "Opens supported sites using HTTPS instead of HTTP when possible", to make it clear to the user that this option only forces SSL for sites that already support it, and can't create a secure connection to a site that doesn't support it.

This more specific description matches the EFF's [project description](https://www.eff.org/https-everywhere), and the description in Brave Laptop ([link](https://github.com/brave/browser-laptop/blob/171e3ac1ce06da42cb24a807966787d1746abaf7/app/locales/en-US/preferences.l20n#L11)).

**Comment by SergeyZhukovsky** [comment]
Thank you. You are right.
Corrected it here
https://github.com/brave/browser-android/commit/0a5a4557c7332de6c1a63a676eee4abacbde9d4b
