### ISSUE TITLE
Hidden Brave browser blocks top part of screen?

### ISSUE THREAD

**Issue by hidroh** [brave/browser-android#722]
I'm not sure how to describe this, but once in a while the top part of my device becomes unusable (there seems to be something blocking me from touching anything on that part of the screen, about the height of Toolbar, regardless of whether the device is in portrait or landscape). I then observe that this seems to be related to Brave browser. This happens some time after I close all my bubbles from a browsing session. Making a new bubble (open any webpage in Brave) then closing it brings things back to normal.

Using:
Brave browser: 1.9.10
OS: Android 6.0.1
Device: Nexus 5X

**Comment by bbondy** [comment]
We recently reproduced this, we'll have a release out asap.

**Comment by SergeyZhukovsky** [comment]
Fixed
https://github.com/brave/browser-android/commit/732a673b53996d267f40337ef5eb8baea85de6ca
Thanks for posting that @hidroh.

**Comment by hidroh** [comment]
Excellent! Thanks!

**Comment by bbondy** [comment]
It was published to the store already, it should be live by tomorrow.
