### ISSUE TITLE
Sometimes there is a text in WebView instead of HTML content

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android#723]
We have noticed that from several customers. It is something related to Brave shields, because they have never seen them when shields are off.

**Comment by bbondy** [comment]
is there a view source mode that somehow gets triggered?

**Comment by SergeyZhukovsky** [comment]
Fixed here
https://github.com/brave/browser-android/commit/9e886203fe3f00690e7018401d57e51162b8bcd2
