### ISSUE TITLE
Back button issue

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android#727]
Back button sometimes doesn't go back on page before and sometimes new bubbles show back arrow immediately.

**Comment by bbondy** [comment]
possibly related to 301, 302, etc redirect codes at the top level? Also possibly check https-everywhere redirected top level pages like apple.com.

**Comment by SergeyZhukovsky** [comment]
It wasn't depend to redirects, it was because of anchors.
Committed here 
https://github.com/brave/browser-android/commit/1b585a7961cd66e22e99bc2632f7b37a3c114114
