### ISSUE TITLE
Add overlay to darken background app behind bubble bar

### ISSUE THREAD

**Issue by bbondy** [brave/browser-android#745]
Some users in support try to click on the things in the background apps and it doesn't work.  Having a dark overlay where the bubbles sit on top of would help.

**Comment by bbondy** [comment]
Please work into an upcoming milestone as per @bradleyrichter's comments.  Also it sometimes does show up so it should just be a bug fix.

**Comment by SergeyZhukovsky** [comment]
Ok. I put it on next Wednesday release.

**Comment by SergeyZhukovsky** [comment]
That was fixed here
https://github.com/brave/browser-android/commit/e034e1a381ca23d2149e9c7d289fa15ec59fad4b
