### ISSUE TITLE
Regular expressions in Domain redirects

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android#749]
Unfortunately currently "Domain redirects" is not support 
regular expression or sub string match.

For example, there are many URLs for same domain("doorkeeper.jp") 
https://jazug.doorkeeper.jp/ 
https://nishinipporirb.doorkeeper.jp/

**Comment by sanpei3** [comment]
I'm original requester.

My idea is below:
Plan A: support regular expression in "Domain redirects"
Plan B: if "Domain redirects" string started with '.'(like ".brave.com"), then sub string match.
             if "Domain redirects" string started without '.', then exact string match.
