### ISSUE TITLE
Browser Bubble Blocks App Content on "N" Preview/Beta

### ISSUE THREAD

**Issue by bigcat** [brave/browser-android#794]
On my recently upgraded Nexus 6P, I'm seeing a behavior where if the bubble is present, I have to move it a little in order for the content on my screen to be interactive.

So, any time I open Brave for any reason - say from Google Now's suggested articles - as soon as it shows it will be as if there is an invisible barrier between my finger and the underlying Google Now screen.  If I move the bubble a little on the side of my screen, then the content in Google Now becomes active again as if the invisible barrier is gone.  The even weirder part is though, if I switch apps, or bring up the task switcher, the invisible layer is back again.  Until I move the bubble a little, or even just start to move it and put it back to where it was.

**Comment by bigcat** [comment]
I saw this stop on the previous version (1.9.51 I believe) and it is back on 1.9.52 that is released in the playstore.

**Comment by okjed** [comment]
I didn't realize moving the bubble would restore functionality. Indeed, unusable on N. Likely my only regret from running N.

**Comment by RyanSinger** [comment]
Same issue.

**Comment by bigcat** [comment]
Still present on release version of Android 7.0 / N.

**Comment by SergeyZhukovsky** [comment]
That was fixed in the latest 1.9.56 release.
