### ISSUE TITLE
Add Sleipnir as a fallback browser

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android#811]
There are several of them. Make sure you've added all ids.

**Comment by bbondy** [comment]
Also Tuga browser

**Comment by bbondy** [comment]
Also browser NB

**Comment by SergeyZhukovsky** [comment]
Also Yandex browser

**Comment by SergeyZhukovsky** [comment]
Also Flyperlink browser
com.flyperinc.flyperlink

**Comment by SergeyZhukovsky** [comment]
Also speed browser

**Comment by SergeyZhukovsky** [comment]
Add YuBrowser

**Comment by kowith337** [comment]
Fennec F-droid [(Forbidden in F-droid but archive repo)](https://f-droid.org/wiki/page/org.mozilla.fennec_fdroid)

IceCatMobile [(F-droid)](https://f-droid.org/repository/browse/?fdid=org.gnu.icecat)

[Pale Moon](https://play.google.com/store/apps/details?id=org.palemoon.android)

**Comment by SergeyZhukovsky** [comment]
Also tubemate

**Comment by mingpowershifter** [comment]
isn't there a browser intent you can build the list from dynamically rather than a specified list?

**Comment by SergeyZhukovsky** [comment]
@mingpowershifter not sure, have to look on it.

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android/commit/0980091f964071b24a12ebab06a551924fff2102
