### ISSUE TITLE
Copy/Paste vs. Performance/Crashes compromise idea

### ISSUE THREAD

**Issue by planeguy** [brave/browser-android#826]
So there was a recent hubbub when a refactor to add copy-paste ended up causing a bunch of problems, and I was thinking of a way we can get the best of both worlds.

I'll admit I'm not a big copy-paster unless I want a quote when I'm doing a share. So for me, I only c/p sometimes and I usually just send the bubble to chrome to do that. With that in mind, I think it might be a good compromise to create an alternate view just for that extra functionality. So like a button to open the bubble in a web view, with the knowledge that the web view bubble will work differently than the default ones. You'd only bother opening it if you needed to do something you couldn't do in a standard brave bubble.

Does anyone do **a lot** of copy-pasting where this might be too much of a bother?

**Comment by bbondy** [comment]
This is what the fallback browser is for. We should use that instead of duplicating a second webview and adding a lot of code.
