### ISSUE TITLE
On Android N, after loading a page in a bubble and minimizing it, I can't click anything except the bubble

### ISSUE THREAD

**Issue by RyanSinger** [brave/browser-android#829]
**Did you search for similar issues before submitting this one?**
No
**Describe the issue you encountered:**
On Android N, after loading a page in a bubble and minimizing it, I can't click anything except the bubble

**Expected behavior:**
I should be able to click other things on the screen, like with Messenger bubbles.
- Android version (4.0, 5.0, ...?):
N
- Brave Version:

- Steps to reproduce:
    1. Open web page in brave
    2. minimize to bubble
    3. try and fail to click anything on the screen except to re-expand the bubble.

- Screenshot if needed:

- Any related issues:

**Comment by iamVP7** [comment]
Reproducible in Nexus 6.

**Comment by gordonsyme** [comment]
I'm seeing the same, Android N Build NPD56N, Brave version 1.9.52

I'm willing to test out dev builds if that helps.

**Comment by Decoherence** [comment]
I'm also seeing this issue in the latest Android N build (NPD90G, Nexus 6P) and Brave 1.9.52.  

Strangely, upon disabling multiprocess WebView in the developer options, Brave functioned as expected--that is, no freezing upon switching apps or returning to the home screen. But this was only temporary; the freezing behavior reoccurred shortly thereafter.

As noted elsewhere, moving the bubble slightly is a temporary workaround.

**Comment by jatwigg** [comment]
same on nexus 5x android N stable release

**Comment by SergeyZhukovsky** [comment]
Done
https://github.com/brave/browser-android/commit/8f820d97aa0a5825954c48f9d96b98ac91a57083

**Comment by rashagen** [comment]
When is this version being released?

**Comment by SergeyZhukovsky** [comment]
@rashagen  it was released this night and it's under review currently. It should appear in a play store today.
