### ISSUE TITLE
Improper Redirection

### ISSUE THREAD

**Issue by iamVP7** [brave/browser-android#848]
**Did you search for similar issues before submitting this one?** 
No

**Describe the issue you encountered:**
I am trying to open https://iamvp7.github.io/2016/08/Running-WebExtension-in-Firefox/ in Android but it is not opening properly and the url gets converts to https://%241.github.io/2016/08/Running-WebExtension-in-Firefox/ 

**Expected behavior:**
Actually the blog posts should have opened properly.

- Android version (4.0, 5.0, ...?): 7.0 in Nexus 6p

- Brave Version: 54.0.2795.0

- Steps to reproduce:
    1. Open Brave in Android
    2. Visit  https://iamvp7.github.io/
    3. Click on Any posts

- Screenshot if needed:

![screenshot_20160907-174632](https://cloud.githubusercontent.com/assets/3106852/18311653/1ce5c2d8-7523-11e6-91c8-52817dba4a74.png)

- Any related issues:

**Comment by bbondy** [comment]
Should this go to brave/chromium?

**Comment by SergeyZhukovsky** [comment]
@iamVP7 could you please move it to brave/chromium?

**Comment by iamVP7** [comment]
Moved to Chromium https://github.com/brave/chromium/issues/12  So closing this issue here.
