### ISSUE TITLE
Give an option for alternative UI

### ISSUE THREAD

**Issue by huuhaa** [brave/browser-android#854]
Don't know if there's a request on this one allready (didn't find any by quick search), but here it goes anyway.

Please give users an option to select between bubble and traditional "mode".

I personally dislike bubble UI, I don't want to see any bubbles anywhere when browser is just at background and I'm using some other app (or other app not opened at all). I also like to be able to close browser from opened app view, but Brave isn't even at the list since it is bubble focused (some version was at list, at least a while though). But anyway as said, I prefer traditional UI over current brave UI, so I don't use Brave for mobile at all. Just test sometimes that what changes updates are bringing to Brave.

I really hope you will fix this, since for me (and I can't believe I'm the only one) this is the biggest issue with mobile version so far. No matter how good it would be otherways, I wouldn't like to use current UI.

**Comment by SergeyZhukovsky** [comment]
@huuhaa we are working on chromium based Android browser with tabs. We are planning to release it soon in October. It is going to be a separate app.

**Comment by SergeyZhukovsky** [comment]
Yep, no relations with Link Bubble.

**Comment by zcdunn** [comment]
@SergeyZhukovsky Will this new browser support Chrome's removed 'merged tabs and apps' feature? I've been looking for a mobile browser that lets me switch tabs within Android's recents menu.

**Comment by SergeyZhukovsky** [comment]
@zcdunn, nope it will not.

**Comment by SergeyZhukovsky** [comment]
@huuhaa , @zcdunn you can download a beta version of new tab based browser from that place
https://drive.google.com/file/d/0B00h0ZE3nmZPVy1uT3JUWlM5ZGM/view?usp=sharing

**Comment by huuhaa** [comment]
Thanks! Tried that at Jolla Sailfish -phone but didn't work. Didn't want to install to android from "unknown source". Anyway it's at Google Play now. Made a swich yesrterday at my Android device + intalled that version to Jolla also. Works great on both platforms! Keep up good working!
