### ISSUE TITLE
Where is the repo for the new Brave Browser in Play Store?

### ISSUE THREAD

**Issue by NQAT** [brave/browser-android#859]
I noticed this one is diffrent than the link bubble one. Diffrent UI, much bigger and asks for access to eveything. https://play.google.com/store/apps/details?id=com.brave.browser&hl=en

**Comment by SergeyZhukovsky** [comment]
Hi @NQAT,
It is in  https://github.com/brave/chromium, but we are going to rename it soon to browser-android

**Comment by NQAT** [comment]
OK, thank you.
