### ISSUE TITLE
Odd behavior w/ Bubble: moving up/down

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-android#868]
From support
> Cuando visualizo una web dentro de la borbuja, esta se mueve hacia arriba y hacia abajo, movimientos raros. 
> Solucionen ese problema

Basically: when viewing a bubble it's seems to have unusual behavior moving up and down (maybe it's jumping up and down? I'll ask for more information)

**Comment by bsclifton** [comment]
User was kind enough to record a video :smile: (I'll share with you on our Slack, @SergeyZhukovsky). In the video, you can see the flickering and jerkiness

**Comment by bsclifton** [comment]
Will be responding with:
1. you can disable bubbles; menu > settings > more > hide bubbles on scroll
2. device may not support animation, which is unlikely as it would have to be old. However, it is possible for folks to turn this off.  This can be checked on the device under Settings > Developer options > Windows animation scale, Transition animation scale, animator duration scale. This requires you to have activated developer options, but maybe it is accidentally set.

**Comment by bsclifton** [comment]
Solved :smile: The user did have animations disabled. Re-enabling this fixed the issue! Closing this ticket

**Comment by SergeyZhukovsky** [comment]
Perfect, thanks :).
